table DimDateTbl
	lineageTag: b900c5a1-b6be-4af9-b499-4c0ec255cabc

	column Date
		dataType: dateTime
		lineageTag: a79ec942-95fb-4cbe-b357-7ea94500cd5a
		sourceColumn: Date

	column DateID
		dataType: int64
		lineageTag: ad276a8b-912e-4b14-9e45-3988c3594814
		sourceColumn: DateID

	column År
		dataType: int64
		lineageTag: 0685a2c4-f31f-47f0-8204-dd3b2b27020c
		sourceColumn: År

	column Måned
		dataType: int64
		lineageTag: 5b15dda6-e1b8-49db-bb59-b768468e39b3
		sourceColumn: Måned

	column MånedNavn
		dataType: string
		lineageTag: b8152922-0a7b-4209-ab04-3d6a46fc7e04
		sourceColumn: MånedNavn

	column Kvartal
		dataType: string
		lineageTag: bcf1850c-0962-4940-8322-ea0f93bf2b9f
		sourceColumn: Kvartal

	column UgeDag
		dataType: string
		lineageTag: 3f9043ad-724f-4896-a14a-9efac886a15b
		sourceColumn: UgeDag

	partition DimDateTbl = m
		mode: import
		source =
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2025, 12, 31),
				    NumberOfDays = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, NumberOfDays, #duration(1, 0, 0, 0)),
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}),
				    ChangedType = Table.TransformColumnTypes(DateTable, {{"Date", type date}}),
				    AddedDateID = Table.AddColumn(ChangedType, "DateID", each Date.Year([Date]) * 10000 + Date.Month([Date]) * 100 + Date.Day([Date]), Int64.Type),
				    AddedYear = Table.AddColumn(AddedDateID, "År", each Date.Year([Date]), Int64.Type),
				    AddedMonth = Table.AddColumn(AddedYear, "Måned", each Date.Month([Date]), Int64.Type),
				    AddedMonthName = Table.AddColumn(AddedMonth, "MånedNavn", each Date.MonthName([Date]), type text),
				    AddedQuarter = Table.AddColumn(AddedMonthName, "Kvartal", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    AddedDayName = Table.AddColumn(AddedQuarter, "UgeDag", each Date.DayOfWeekName([Date]), type text)
				in
				    AddedDayName

